### ISSUE TITLE
Dream Soccer Flickering Issues

### ISSUE THREAD

**Issue by harlock74** [MiSTer-devel/Arcade-IremM92_MiSTer#10]
Hi there,
When you get a chance, would you please be so kind s to investigate the following issue with Dream Soccer?
Occassionally roughly a quarter of the screen gets all black or parts of the screen get overlapped. Also while approaching the proximity of the goalkeeper's area of the opposite team the right part of the screen starts flickering (the area where the photographers are).
Many thanks!

![1684092281618](https://github.com/MiSTer-devel/Arcade-IremM92_MiSTer/assets/4136670/44a3d0de-ceaa-44a0-86fd-2742eded3d36)

**Comment by wickerwaka** [comment]
Fixed by 5ae29992869f560dbb1f5430c4c89082f7685c58

**Comment by harlock74** [comment]
Awesome, thanks so much!
