### ISSUE TITLE
 HQ2X scandoubler effect missing

### ISSUE THREAD

**Issue by TTurbo23** [MiSTer-devel/Arcade-IremM92_MiSTer#11]
Request to add HQ2X to m92.

This is also missing from other irem cores.

Thanks.

**Comment by TTurbo23** [comment]
Hi Martin,

Thank you very much for all your work.

Will this be available after an update all soon?


Regards,
Terry.
________________________________

**Comment by wickerwaka** [comment]
I need to build a new release but I'm not going to do that because I am going to be traveling for a few days and so won't be around if the release causes any problems. I will do a release early next week.

**Comment by TTurbo23** [comment]
Ok cool and enjoy your time travelling.

By the way It was just a query as the request was closed and completed, so not demanding.

Your work on the mister is outstanding and truly appreciated.


Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
