### ISSUE TITLE
Undercover Cops Alpha MRAs need fixing?

### ISSUE THREAD

**Issue by alessioscand** [MiSTer-devel/Arcade-IremM92_MiSTer#12]
Sorry for writing here even though I'm getting the issues on SiDi, but it seems to concern MRA files.

In Undercover Cops Alpha Renewal Version (both US and World) dipswitches seem to have some problems (they don't appear in the appropriate submenu, the flip screen is like pause etc.). 

Thank you so much for this great core! ;)

**Comment by Toryalai1** [comment]
Did you try this on the MiSTer or SiDi? 
Please note that this repo is for the MiSTer

**Comment by alessioscand** [comment]
Yes, but taking the MRA from this repository, so it *should be* a common problem.
Do Undercover Cops ALPHA RENEWAL VERSION dip switches work properly on MiSTer? 

Thank you

**Comment by alessioscand** [comment]
OK, the MRAs were missing some specific instructions for MiST and SiDi. I close the issue (I'm very sorry!)
