### ISSUE TITLE
IREM M92 Core issue with "In the Hunt" JAP verson.

### ISSUE THREAD

**Issue by mhmetalheart** [MiSTer-devel/Arcade-IremM92_MiSTer#14]
that jap verson, score uncorrect, it will change with moving i/o show correct scores. But in Turbo M92 core. That is correct.

**Comment by mhmetalheart** [comment]
https://www.youtube.com/watch?v=FRK06BKOraM

The new version 240424 still have same issue. But I ask some friends to test it. They said good. I don't know why. I even change the mame rom to newest.
The video also show 230517 turbo core. The score is correct. Please help.

**Comment by wickerwaka** [comment]
You likely have a corrupt hi score nvram file from the turbo core. Go to the `config/nvram` directory on your sdcard (using whatever method works best for you) and delete or rename the `In The Hunt (Japan).nvm` file.

**Comment by mhmetalheart** [comment]
done! YEP. Kaitei Daisensou (Japan).nvm deleted and everything all OK now! Thanks.
