### ISSUE TITLE
Analog V-Position settings above +6 result in the HDMI image wrapping around the screen.

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Arcade-IremM92_MiSTer#6]
7 and above for the V-position setting will wrap the image on the screen, making more bottom-row pixels show up at the top of the screen the further you go.

The M92 has really funky alignment and screen fill on CRT's, so most folks are going to use these settings.  This will hinder recording while playing on CRT's, or require the user to reset the position when they switch between analog/HDMI.

**Comment by wickerwaka** [comment]
This is just the nature of how this feature works. It is adjusting the video signal so in the extremes it is going to cause picture to start wrapping around.
