### ISSUE TITLE
In The Hunt - Player getting stuck when dying at same time as trapped in ice. Possibly not a core issue.

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Arcade-IremM92_MiSTer#7]
This will be hard to reproduce because it requires dying on your last life & continuing at the same time as being trapped in ice on the first stage, and possibly only happens in the location in this video I recorded:

https://youtu.be/IfMwPOVMzQc

You can see where my ship is stuck off the screen on the left side when I fire.  I'm unsure as to whether  a timer ran down on the ice blob that was supposed to trap my ship, or spamming fire buttons caused me to eventually re-gain movement control.  This could likely be an original game quirk.

**Comment by wickerwaka** [comment]
Fixed by 5ae29992869f560dbb1f5430c4c89082f7685c58
